# This docker compose is for development

version: "3.7"

services:
  postgresql:
    image: bitnami/postgresql:15.3.0-debian-11-r14
    container_name: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
     - 5432:5432
    restart: always
    environment:
      # POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_DB: postgres
      # POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgadmin:
    image: dpage/pgadmin4:7.3
    container_name: pgadmin
    volumes:
      - pgadmin4:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.net
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80
  redis:
    image: redis:alpine3.18
    container_name: redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
  nats:
    image: nats:2.9.19
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
  nats-1:
    image: nats:2.9.19
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on: ["nats"]
  nats-2:
    image: nats:2.9.19
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on: ["nats"]
volumes:
  postgresql:
  pgadmin4:
